@startuml
class com.example.refresh.Adapter.FoodSelectionsAdapter {
- ArrayList<ListItem<Food>> foodSelections
- SelectedFoodsFragment fragment
}

class com.example.refresh.Adapter.FoodSelectionsAdapter$FoodSelectionViewHolder {
- TextView titleTV
- TextView descriptionTV
- ImageButton removeBtn
- LinearLayout itemContainer
}

class com.example.refresh.Adapter.SearchResultsAdapter {
- ArrayList<ListItem<Food>> resultsList
- SearchResultsFragment fragment
}

class com.example.refresh.Adapter.SearchResultsAdapter$ResultViewHolder {
- TextView titleTV
- TextView descriptionTV
- ImageButton addBtn
- LinearLayout itemContainer
}

class com.example.refresh.Model.ListItem {
- String title
- String description
- T model
}

class com.example.refresh.Fragment.DailyProgressFragment {
- ProgressBar caloriesProgress
- TextView caloriesText
- int totalCalories
- int totalCarbs
- int totalProtein
- int totalFat
}

class com.example.refresh.Model.NotificationInstance {
- int instanceID
- int templateID
- String time
}

class com.example.refresh.Model.DaySummary {
- LocalDate day
- ArrayList<Meal> meals
- int mealCount
- int totalCalories
- int totalCarbs
- int totalProtein
- int totalFat
- int totalWater
}

class com.example.refresh.Notification.BootReceiver {
}
class com.example.refresh.Fragment.FoodInfoFragment {
- Food food
- OnFoodInfoFragmentListener fragmentListener
- ArrayList<String> solidServingOptions
- ArrayList<String> liquidServingOptions
- {static} Map<String,Integer> SOLID_SERVING_MAP
- {static} Map<String,Integer> LIQUID_SERVING_MAP
- TextView title
- ImageButton backBtn
- ImageButton extraBtn
- TextView foodNameTV
- ImageButton favoriteBtn
- TextView descriptionTV
- EditText servingCountET
- Spinner servingOptionSpinner
- CircularProgressBar carbsProgressBar
- TextView carbsProgressTV
- CircularProgressBar proteinProgressBar
- TextView proteinProgressTV
- CircularProgressBar fatProgressBar
- TextView fatProgressTV
- SeekBar caloriesSeekBar
- TextView carbsTV
- TextView proteinTV
- TextView fatTV
- TextView caloriesTV
- Button addBtn
}

interface com.example.refresh.Fragment.FoodInfoFragment$OnFoodInfoFragmentListener {
}
class com.example.refresh.Activity.HomeDashboardActivity {
- FragmentContainerView userInfoContainer
- BottomNavigationView bottomNavigation
- LocalDate currentDate
- DaySummary daySummary
- DailySummaryHelper dailySummaryHelper
- WaterLogHelper waterLogHelper
- UserInfoHelper userInfoHelper
- TextView title
- ImageButton nextBtn
- ImageButton prevBtn
- LinearLayout logWaterBtn
- LinearLayout logMealBtn
- LinearLayout logWeightBtn
- ImageButton profileBtn
- ImageButton notificationBtn
- TextView weightProgressLabel
- TextView weightProgressValue
}

class com.example.refresh.Activity.MealLogActivity {
- Meal meal
- ArrayList<Food> mealFoods
- LocalDate mealDate
- LocalTime mealTime
- LocalDate oldDate
- TextView title
- TextView mealDateTimeTV
- ImageButton backBtn
- ImageButton datePickerBtn
- EditText searchBarET
- ImageButton clearBtn
- FragmentContainerView searchResultsContainer
- FragmentContainerView selectedFoodsContainer
- FragmentContainerView foodInfoFragmentContainer
- SelectedFoodsFragment selectedFoodsFragment
- FoodInfoFragment foodInfoFragment
- EditText notesET
- Button logMealBtn
- BottomNavigationView bottomNavigationView
- boolean inEditMode
}

class com.example.refresh.Activity.ProfileActivity {
- ImageView backArrow
- TextView toolbarTitle
- ImageButton settingsButton
- ImageView profilePicture
- TextView profileName
- FragmentContainerView fragmentContainer
}

class com.example.refresh.ExampleInstrumentedTest {
}
class com.example.refresh.Fragment.TrendGraphFragment {
- BarChart chart
}

class com.example.refresh.Notification.NotificationReceiver {
}
class com.example.refresh.Helper.UserInfoHelper {
- int userId
- Context context
- SharedPreferences userPreferences
}

class com.example.refresh.Database.UsersTable {
+ {static} String TABLE_NAME
+ {static} String CREATE_TABLE
}

enum com.example.refresh.Database.Columns {
+  ID
+  NAME
+  EMAIL
+  PHONE
+  PWD
+  PWD_CONFIRM
- String columnName
}

class com.example.refresh.Database.NotificationInstancesTable {
+ {static} String TABLE_NAME
+ {static} String CREATE_TABLE
}

enum com.example.refresh.Database.Columns {
+  INSTANCE_ID
+  TEMPLATE_ID
+  TIME
- String columnName
}

class com.example.refresh.StartActivity {
- TextView cdtTV
- Button continueBTN
- CountDownTimer timer
- {static} String PREFS_NAME
- {static} String FIRST_LAUNCH_KEY
- {static} String LOGGED_USER_ID_KEY
}

class com.example.refresh.Model.ErrorMessage {
- Columns field
- String message
}

class com.example.refresh.Fragment.SelectedFoodsFragment {
- ArrayList<ListItem<Food>> selectedFoods
- OnSelectedFoodsFragmentListener fragmentListener
- FoodSelectionsAdapter foodsAdapter
- RecyclerView foodsRV
}

interface com.example.refresh.Fragment.SelectedFoodsFragment$OnSelectedFoodsFragmentListener {
}
class com.example.refresh.Helper.NotificationHelper {
- {static} String TAG
+ {static} String CHANNEL_ID
- {static} int DEFAULT_NOTIFICATION_ID
}

class com.example.refresh.Model.Meal {
- int id
- LocalDate date
- LocalTime time
- String type
- ArrayList<Integer> foodIDs
- ArrayList<Integer> servingSizes
- int userID
- String notes
}

class com.example.refresh.Model.User {
- int id
- String name
- String email
- String phone
- String pwd
}

class com.example.refresh.Database.NotificationTemplatesTable {
+ {static} String TABLE_NAME
+ {static} String JSON_FILE_NAME
+ {static} String CREATE_TABLE
}

enum com.example.refresh.Database.Columns {
+  TEMPLATE_ID
+  CATEGORY
+  TITLE
+  MESSAGE
+  ICON_ID
+  ACTIVITY_CLASS
- String columnName
}

class com.example.refresh.ExampleUnitTest {
}
class com.example.refresh.Activity.SignUpActivity {
- EditText nameET
- Button signUpBtn
- TextView loginBtn
- User user
- DatabaseHelper dbHelper
}

class com.example.refresh.Notification.NotificationScheduler {
}
class com.example.refresh.Fragment.SearchResultsFragment {
- ArrayList<ListItem<Food>> searchResults
- OnSearchResultsFragmentListener fragmentListener
- SearchResultsAdapter searchResultsAdapter
- RecyclerView resultsRV
- TextView noResultsTV
}

interface com.example.refresh.Fragment.SearchResultsFragment$OnSearchResultsFragmentListener {
}
class com.example.refresh.Helper.DailySummaryHelper {
- DatabaseHelper dbHelper
- Context context
}

class com.example.refresh.Notification.AppNotificationChannel {
+ {static} String CHANNEL_ID
+ {static} String CHANNEL_NAME
+ {static} String CHANNEL_DESCRIPTION
}

class com.example.refresh.Fragment.UserInfoFragment {
- String state
- int userId
- User user
- OnUserInfoFragmentListener fragmentListener
- ArrayList<String> displayedSections
- UserInfoHelper userInfoHelper
- DatabaseHelper dbHelper
- ArrayList<String> genderOptions
- ArrayList<String> activityLevelOptions
- LinearLayout personalInfoLayout
- LinearLayout accountDetailsLayout
- LinearLayout lifestyleGoalLayout
- LinearLayout adjustGoalLayout
- LinearLayout targetWeightLayout
- TextView title
- ImageButton saveBtn
- ImageButton backBtn
- EditText nameET
- EditText weightET
- EditText heightET
- EditText dateOfBirthET
- Spinner genderSpinner
- TextView genderErrorTV
- EditText emailET
- EditText phoneET
- EditText pwdET
- RadioGroup goalRG
- RadioButton loseWeightRB
- RadioButton maintainWeightRB
- RadioButton gainWeightRB
- RadioButton gainMuscleRB
- TextView goalErrorTV
- EditText targetWeightET
- Spinner activityLevelSpinner
- TextView activityLevelErrorTV
- RadioGroup dietTypeRG
- RadioButton carnivoreRB
- RadioButton vegetarianRB
- RadioButton veganRB
- TextView dietTypeErrorTV
- EditText adjustCaloriesET
- EditText adjustCarbsET
- EditText adjustProteinET
- EditText adjustFatET
- EditText adjustWaterIntakeET
}

interface com.example.refresh.Fragment.UserInfoFragment$OnUserInfoFragmentListener {
}
enum com.example.refresh.Fragment.States {
+  ALL
+  FIRST_LOG
+  PERSONAL_INFO
+  ACCOUNT_DETAILS
+  LIFESTYLE_GOAL
+  ADJUST_GOAL
+  MULTIPLE
- String stateName
}

class com.example.refresh.MyApplication {
- {static} MyApplication instance
+ {static} String PREFS_NAME
+ {static} String LOGGED_USER_ID_KEY
+ {static} String LOGGED_USER_SP_NAME_KEY
+ {static} String FIRST_LAUNCH_KEY
}

class com.example.refresh.Helper.ValidationHelper {
}
class com.example.refresh.TestingGrounds {
- {static} String TIME_FORMAT_PATTERN
}

class com.example.refresh.Activity.ProgressActivity {
- ArrayList<Meal> weekMeals
- ArrayList<DaySummary> daySummaries
- LocalDate currentWeekStart
- Toolbar toolbar
- TextView title
- ImageButton refreshBtn
- ImageButton ExtraBtn
- TextView WeekDatesTV
- ImageButton lastWeekBtn
- ImageButton nextWeekBtn
- RecyclerView mealsRV
- SectionedRecyclerViewAdapter sectionAdapter
- BottomNavigationView bottomNavigation
- FragmentContainerView weekGraphContainer
- TrendGraphFragment trendGraphFragment
- SharedPreferences userSP
- DailySummaryHelper dailySummaryHelper
- ActivityResultLauncher<Intent> editMealLauncher
}

class com.example.refresh.Adapter.DaySection {
- String day
- ArrayList<ListItem<Meal>> mealItems
- OnEditMealListener editMealListener
- OnDeleteMealListener deleteMealListener
}

interface com.example.refresh.Adapter.DaySection$OnEditMealListener {
}
interface com.example.refresh.Adapter.DaySection$OnDeleteMealListener {
}
class com.example.refresh.Adapter.DaySection$MealViewHolder {
- TextView mealTitleTV
- TextView mealDescriptionTV
- ImageButton removeBtn
- ImageButton editBtn
- LinearLayout itemContainer
}

class com.example.refresh.Adapter.DaySection$DayHeaderViewHolder {
- TextView headerTitleTV
}

class com.example.refresh.Helper.DatabaseHelper {
- {static} String DATABASE_FILE
- {static} int DATABASE_VERSION
- Context context
}

enum com.example.refresh.Helper.Tables {
+  USERS
+  NOTIFICATION_TEMPLATES
+  NOTIFICATION_INSTANCES
+  FOODS
+  MEALS
- String tableName
}

class com.example.refresh.Helper.WaterLogHelper {
- DatabaseHelper dbHelper
- Context context
}

class com.example.refresh.Database.MealsTable {
+ {static} String TABLE_NAME
+ {static} String CREATE_TABLE
}

enum com.example.refresh.Database.Columns {
+  MEAL_ID
+  DATE
+  TIME
+  TYPE
+  NOTES
+  FOOD_IDS
+  SERVING_SIZES
+  USER_ID
- String columnName
}

class com.example.refresh.Database.FoodsTable {
+ {static} String TABLE_NAME
+ {static} String JSON_FILE_NAME
+ {static} String CREATE_TABLE
}

enum com.example.refresh.Database.Columns {
+  FOOD_ID
+  NAME
+  DESCRIPTION
+  CATEGORY
+  LABEL
+  SERVING_SIZE
+  CALORIES
+  CARBS
+  PROTEIN
+  FAT
+  NOTES
- String columnName
}

class com.example.refresh.Activity.LoginActivity {
- EditText emailET
- EditText pwdET
- Button loginBtn
- CheckBox rememberMeCB
- TextView signUpBtn
- DatabaseHelper dbHelper
}

class com.example.refresh.Model.Food {
- int id
- String name
- String description
- String category
- ArrayList<String> labels
- int servingSize
- int calories
- int carbs
- int protein
- int fat
- String notes
}

class com.example.refresh.Model.NotificationTemplate {
- int templateID
- String category
- String title
- String message
- int iconID
- Class<?> activityClass
- {static} Map<String,Integer> iconMap
}



com.example.refresh.Adapter.Adapter <|-- com.example.refresh.Adapter.FoodSelectionsAdapter
com.example.refresh.Adapter.FoodSelectionsAdapter +.. com.example.refresh.Adapter.FoodSelectionsAdapter$FoodSelectionViewHolder
com.example.refresh.Adapter.ViewHolder <|-- com.example.refresh.Adapter.FoodSelectionsAdapter$FoodSelectionViewHolder
com.example.refresh.Adapter.Adapter <|-- com.example.refresh.Adapter.SearchResultsAdapter
com.example.refresh.Adapter.SearchResultsAdapter +.. com.example.refresh.Adapter.SearchResultsAdapter$ResultViewHolder
com.example.refresh.Adapter.ViewHolder <|-- com.example.refresh.Adapter.SearchResultsAdapter$ResultViewHolder
java.io.Serializable <|.. com.example.refresh.Model.ListItem
androidx.fragment.app.Fragment <|-- com.example.refresh.Fragment.DailyProgressFragment
java.io.Serializable <|.. com.example.refresh.Model.DaySummary
android.content.BroadcastReceiver <|-- com.example.refresh.Notification.BootReceiver
androidx.fragment.app.Fragment <|-- com.example.refresh.Fragment.FoodInfoFragment
com.example.refresh.Fragment.FoodInfoFragment +.. com.example.refresh.Fragment.FoodInfoFragment$OnFoodInfoFragmentListener
com.example.refresh.Activity.OnUserInfoFragmentListener <|.. com.example.refresh.Activity.HomeDashboardActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.refresh.Activity.HomeDashboardActivity
com.example.refresh.Activity.OnSearchResultsFragmentListener <|.. com.example.refresh.Activity.MealLogActivity
com.example.refresh.Activity.OnSelectedFoodsFragmentListener <|.. com.example.refresh.Activity.MealLogActivity
com.example.refresh.Activity.OnFoodInfoFragmentListener <|.. com.example.refresh.Activity.MealLogActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.refresh.Activity.MealLogActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.refresh.Activity.ProfileActivity
androidx.fragment.app.Fragment <|-- com.example.refresh.Fragment.TrendGraphFragment
android.content.BroadcastReceiver <|-- com.example.refresh.Notification.NotificationReceiver
androidx.appcompat.app.AppCompatActivity <|-- com.example.refresh.StartActivity
androidx.fragment.app.Fragment <|-- com.example.refresh.Fragment.SelectedFoodsFragment
com.example.refresh.Fragment.SelectedFoodsFragment +.. com.example.refresh.Fragment.SelectedFoodsFragment$OnSelectedFoodsFragmentListener
java.io.Serializable <|.. com.example.refresh.Model.Meal
androidx.appcompat.app.AppCompatActivity <|-- com.example.refresh.Activity.SignUpActivity
androidx.fragment.app.Fragment <|-- com.example.refresh.Fragment.SearchResultsFragment
com.example.refresh.Fragment.SearchResultsFragment +.. com.example.refresh.Fragment.SearchResultsFragment$OnSearchResultsFragmentListener
androidx.fragment.app.Fragment <|-- com.example.refresh.Fragment.UserInfoFragment
com.example.refresh.Fragment.UserInfoFragment +.. com.example.refresh.Fragment.UserInfoFragment$OnUserInfoFragmentListener
com.example.refresh.Application <|-- com.example.refresh.MyApplication
androidx.appcompat.app.AppCompatActivity <|-- com.example.refresh.Activity.ProgressActivity
io.github.luizgrp.sectionedrecyclerviewadapter.Section <|-- com.example.refresh.Adapter.DaySection
com.example.refresh.Adapter.DaySection +.. com.example.refresh.Adapter.DaySection$OnEditMealListener
com.example.refresh.Adapter.DaySection +.. com.example.refresh.Adapter.DaySection$OnDeleteMealListener
com.example.refresh.Adapter.DaySection +.. com.example.refresh.Adapter.DaySection$MealViewHolder
com.example.refresh.Adapter.ViewHolder <|-- com.example.refresh.Adapter.DaySection$MealViewHolder
com.example.refresh.Adapter.DaySection +.. com.example.refresh.Adapter.DaySection$DayHeaderViewHolder
com.example.refresh.Adapter.ViewHolder <|-- com.example.refresh.Adapter.DaySection$DayHeaderViewHolder
android.database.sqlite.SQLiteOpenHelper <|-- com.example.refresh.Helper.DatabaseHelper
androidx.appcompat.app.AppCompatActivity <|-- com.example.refresh.Activity.LoginActivity
java.io.Serializable <|.. com.example.refresh.Model.Food
@enduml